---
- name: run echo-server
  hosts: all
  tasks:
    - name: run echo-server
      docker_container:
        name: echo-sample-web
        image: jmalloc/echo-server:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
