---
- name: create tmp file to test ansible
  hosts: all
  tasks:
    - name: create tmp file
      file:
        path: /tmp/ansible-testtmpfile
        state: touch
        mode: u=rw,g=r,o=r

    - name: get stat of tmp file
      file:
        path: /tmp/ansible-testtmpfile
        state: file
      register: tmpfile

    - debug:
        var: tmpfile
